<?php

namespace Annonces\MainBundle\Repository;

/**
 * answerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class answerRepository extends \Doctrine\ORM\EntityRepository
{
}
