<?php

namespace Annonces\MainBundle\Repository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCategories(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AnnoncesMainBundle:category c ORDER BY c.name ASC '
            )
            ->getResult();
    }
}
